Repository udplabs/zartan, pull requests merged in 2020-09, with the labels that each got.

#339 Update release-drafter-config.yml
  .github/release-drafter-config.yml
Labels: type: maintenance

#146 Add dockerization feature
  Dockerfile
  README.md
  docker-compose.yml
Labels: type: docs, type: feature

#335 Feature/device flow
  _streamingservice/templates/streamingservice/device_activate.html
  _streamingservice/templates/streamingservice/device_complete.html
  _streamingservice/templates/streamingservice/device_register.html
  _streamingservice/templates/streamingservice/devicepage.html
  _streamingservice/templates/streamingservice/navitems.html
  _streamingservice/templates/streamingservice/navitemslogin.html
  _streamingservice/templates/streamingservice/template.html
  _streamingservice/views.py
  config/app_config.py
  utils/okta.py
Labels: type: feature

#333 Added informational dialog to show IDP ACS URL and metadata file.
  GlobalBehaviorandComponents/idpmanagement.py
  GlobalBehaviorandComponents/login.py
  GlobalBehaviorandComponents/templates/managesamlidps.html
  utils/okta.py
Labels: type: maintenance

#336 fix name truncate issue on manage users
  GlobalBehaviorandComponents/templates/manageusers.html
Labels: type: bug

#340 Add ability to use own SparkPost account
  .env.sample
  config/app_config.py
  docs/README.md
  utils/email.py
Labels: type: feature

#346 Update docker-compose.yml
  docker-compose.yml
Labels: type: maintenance

#347 Update terraform section to explicitly mention support for v0.12
  docs/README.md
Labels: type: docs

#349 Added Device Management and Info Windows
  _streamingservice/templates/streamingservice/device_activate.html
  _streamingservice/templates/streamingservice/device_complete.html
  _streamingservice/templates/streamingservice/device_register.html
  _streamingservice/templates/streamingservice/devicepage.html
  _streamingservice/templates/streamingservice/mydevices.html
  _streamingservice/templates/streamingservice/navitemslogin.html
  _streamingservice/views.py
  utils/okta.py
Labels: type: feature

#353 Add the Feature section back to the README
  README.md
Labels: type: bug, type: docs

#352 UI Fixes and Fixed Page Error from Sublinks
  _dealer/templates/dealer/myapps.html
  _dealer/templates/dealer/navitemslogin.html
  _dealer/templates/dealer/workflow-approvals.html
  _dealer/templates/dealer/workflow-requests.html
  _dealer/views.py
Labels: type: bug

#354 Streaming Service TF and Admin Login Fix
  _admin/templates/admin/index.html
  _streamingservice/templates/streamingservice/devicepage.html
  terraform/streamingservice/streamingservice.tf
Labels: type: feature

#355 bug fix due to last deployment on request pages
  GlobalBehaviorandComponents/stepupauth.py
  GlobalBehaviorandComponents/userapps.py
  _dealer/templates/dealer/workflow-approvals.html
  _dealer/templates/dealer/workflow-requests.html
  _streamingservice/templates/streamingservice/devicepage.html
Labels: type: bug

#356 Apply Remote Config Hot Fix to Streaming
  _streamingservice/views.py
Labels: type: bug

#357 Updated all routes with Apply Config
  GlobalBehaviorandComponents/idpmanagement.py
  GlobalBehaviorandComponents/idverification.py
  GlobalBehaviorandComponents/mfaenrollment.py
  README.md
  _admin/views.py
  _b2b/views.py
  _credit/views.py
  _dealer/views.py
  _ecommerce/views.py
  _finance/views.py
  _healthcare/views.py
  _hospitality/views.py
  _sample/views.py
  _streamingservice/views.py
  _travelagency/views.py
Labels: type: bug

#358 Added Okta Hosted Login
  GlobalBehaviorandComponents/login.py
  GlobalBehaviorandComponents/templates/components/template-navigation-custom-login.html
  GlobalBehaviorandComponents/templates/components/template-navigation-widget-login.html
  GlobalBehaviorandComponents/templates/components/template-navigation.html
Labels: type: feature

#360 Added Device ID to Refresh Request
  _streamingservice/views.py
Labels: type: feature

#362 Fix Product Page on Ecommerce Demo
  _ecommerce/views.py
Labels: type: bug

#363 fixed text on ecommerce shop page
  _ecommerce/templates/ecommerce/cart.html
Labels: type: feature

#366 Fixed update user bug
  _ecommerce/views.py
Labels: type: bug

#368 Fixed popup issue and added name for Temp Passcode
  _admin/templates/admin/template.html
  _admin/views.py
Labels: type: bug

#371 Fixed login redirect for Admin
  _admin/templates/admin/template.html
Labels: type: bug

#373 Add User Tracking
  GlobalBehaviorandComponents/templates/components/template-header-meta-admin.html
  GlobalBehaviorandComponents/templates/components/template-header-meta.html
Labels: type: feature
