Repository udplabs/zartan, pull requests merged in 2020-10, with the labels that each got.

#377 Feature/add idp custom login flow
  GlobalBehaviorandComponents/login.py
  GlobalBehaviorandComponents/templates/components/template-navigation-custom-login.html
Labels: type: feature

#384 Fixed HTML issue with language selection mapping in login screen
  GlobalBehaviorandComponents/templates/components/template-login-widget.html
Labels: type: bug

#383 Added Code Verification for Users
  _admin/templates/admin/users_advanced.html
  _admin/views.py
  utils/okta.py
Labels: type: feature

#387 Applied update per dependabot warning
  requirements/common.txt
Labels: type: dependencies
