Repository udplabs/zartan, pull requests merged in 2020-08, with the labels that each got.

#288 Added new B2B Vertical
  _b2b/templates/b2b/index.html
  _b2b/templates/b2b/login.html
  _b2b/templates/b2b/navitems.html
  _b2b/templates/b2b/navitemslogin.html
  _b2b/templates/b2b/profile.html
  _b2b/templates/b2b/template.html
  _b2b/templates/b2b/workflow-approvals.html
  _b2b/templates/b2b/workflow-requests.html
  _b2b/views.py
  app.py
  utils/okta.py
Labels: blocked

#319 Add GH Actions for manual deployment to EBS
  .github/workflows/deployment.yml
Labels: enhancement, size/S

#320 Update name for consistency
  .github/workflows/deployment.yml
  .github/workflows/python.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, size/XS

#316 Feature/update Ecomm product loc
  _ecommerce/views.py
  config/app_config.py
  terraform/ecommerce/ecommerce.dotenv.template
  terraform/ecommerce/ecommerce.tf
  terraform/ecommerce/ecommerce.tf.none
  terraform/ecommerce/ecommerce.tfvars.sample
Labels: blocked

#317 Added TF for Ecommerce
  terraform/ecommerce/ecommerce.dotenv.template
  terraform/ecommerce/ecommerce.tf
  terraform/ecommerce/ecommerce.tf.none
  terraform/ecommerce/ecommerce.tfvars.sample
Labels: enhancement

#327 fixed https issue with idp federated login
  GlobalBehaviorandComponents/templates/components/template-login-widget.html
Labels: bug

#328 Add gh-actions deployment all zartan ebs
  .github/workflows/deployment-all.yml
  .github/workflows/deployment-single.yml
Labels: enhancement, size/S
