Repository udplabs/zartan, pull requests merged in 2020-07, with the labels that each got.

#228 Update README.md
  docs/README.md
Labels: documentation

#248 Fixed default value in field
  utils/udp.py
Labels: bug

#239 Idp admin screen
  GlobalBehaviorandComponents/idpmanagement.py
  GlobalBehaviorandComponents/templates/components/template-navigation-admin.html
  GlobalBehaviorandComponents/templates/managesamlidp.html
  GlobalBehaviorandComponents/templates/managesamlidps.html
  app.py
  requirements/common.txt
  utils/okta.py
Labels: enhancement
