Repository udplabs/zartan, pull requests merged in 2021-03, with the labels that each got.

#420 Create API Service App
  GlobalBehaviorandComponents/manageapps.py
  GlobalBehaviorandComponents/templates/components/template-manageapps-createupdate.html
  GlobalBehaviorandComponents/templates/components/template-manageapps.html
  GlobalBehaviorandComponents/templates/components/template-navigation-admin.html
  GlobalBehaviorandComponents/templates/manageappcreateupdate.html
  GlobalBehaviorandComponents/templates/manageapps.html
  GlobalBehaviorandComponents/templates/manageusers.html
  app.py
  utils/okta.py
Labels: size/M, type: feature

#423 Linked Objects
  GlobalBehaviorandComponents/linkedobjects.py
  GlobalBehaviorandComponents/manageapps.py
  GlobalBehaviorandComponents/manageusers.py
  GlobalBehaviorandComponents/templates/components/template-navigation-admin.html
  GlobalBehaviorandComponents/templates/manageappscreateupdate.html
  GlobalBehaviorandComponents/templates/managelinkedobjects.html
  GlobalBehaviorandComponents/templates/manageschemas.html
  GlobalBehaviorandComponents/templates/manageschemascreate.html
  GlobalBehaviorandComponents/templates/manageusers.html
  GlobalBehaviorandComponents/templates/manageuserscreateupdate.html
  _admin/templates/admin/adminhome.html
  _sample/templates/sample/navitemslogin.html
  app.py
  utils/okta.py
Labels: type: feature

#425 Update README.md
  README.md
Labels: type: docs

#433 Fixed User Create Bug
  GlobalBehaviorandComponents/manageusers.py
Labels: type: bug

#434 Fix User Create Bug
  GlobalBehaviorandComponents/manageusers.py
Labels: type: bug
