Repository udplabs/zartan, pull requests merged in 2021-01, with the labels that each got.

#412 Update docker-compose
  README.md
  docker-compose.yml
Labels: type: maintenance

#415 Feature: Update widget js and enable webauthn
  GlobalBehaviorandComponents/mfaenrollment.py
  GlobalBehaviorandComponents/templates/components/template-login-widget-pwless.html
  GlobalBehaviorandComponents/templates/components/template-login-widget.html
  GlobalBehaviorandComponents/templates/components/template-mfaenrollment.html
  GlobalBehaviorandComponents/templates/components/template-navigation-custom-login.html
  GlobalBehaviorandComponents/templates/components/template-navigation.html
  _admin/templates/admin/index.html
  _dealer/templates/dealer/registration-state.html
  _streamingservice/templates/streamingservice/device_activate.html
  _streamingservice/templates/streamingservice/device_complete.html
  _streamingservice/templates/streamingservice/device_register.html
  utils/okta.py
Labels: type: feature

#416 Fixed Factor list and multiple WebAuthN
  GlobalBehaviorandComponents/mfaenrollment.py
  GlobalBehaviorandComponents/templates/components/template-mfaenrollment.html
Labels: type: bug
