Repository udplabs/zartan, pull requests merged in 2022-01, with the labels that each got.

#469 Upgraded the widget and updated the location of the widget js imports
  GlobalBehaviorandComponents/templates/components/template-login-widget-pwless.html
  GlobalBehaviorandComponents/templates/components/template-login-widget.html
  GlobalBehaviorandComponents/templates/components/template-navigation.html
  terraform/healthcare/healthcare.tf
Labels: type: feature

#472 Fix issue with new audience config/env setting to handle local token validation
  GlobalBehaviorandComponents/validation.py
  tests/utils/test_udp.py
  utils/udp.py
Labels: type: bug

#473 Fixed missing reference to the admin login screen missing 'dumps' reference
  GlobalBehaviorandComponents/login.py
Labels: type: bug

#474 added comment
  GlobalBehaviorandComponents/login.py
Labels: type: feature

#475 Feature/demo buttons
  GlobalBehaviorandComponents/templates/components/template-idverification.html
  GlobalBehaviorandComponents/templates/components/template-mfaenrollment.html
Labels: type: feature

#476 Bug/fix endless auth loop
  GlobalBehaviorandComponents/templates/components/template-login-widget-oie.html
  GlobalBehaviorandComponents/templates/components/template-singlesignon.html
  utils/okta.py
  utils/udp.py
Labels: type: bug

#480 Update README.md
  docs/README.md
Labels: type: docs

#477 Bug/fix dumps jinja issue
  GlobalBehaviorandComponents/login.py
  GlobalBehaviorandComponents/templates/components/template-login-widget-oie.html
  GlobalBehaviorandComponents/templates/components/template-login-widget-pwless.html
  GlobalBehaviorandComponents/templates/components/template-login-widget.html
  utils/udp.py
Labels: type: bug

#479 Fix submit button bug on the factor screen
  GlobalBehaviorandComponents/templates/components/template-mfaenrollment.html
  static/js/mfa_enrollment.js
Labels: type: bug

#482 Removed redirect URI override code that caused error
  utils/udp.py
Labels: type: bug

#483 Fixed local JWT validation
  GlobalBehaviorandComponents/validation.py
  requirements/common.txt
  utils/okta.py
Labels: type: bug

#484 Update common.txt
  requirements/common.txt
Labels: type: bug

#485 Fix healthcare oie profile bug
  .env.sample
  GlobalBehaviorandComponents/validation.py
  _healthcareoie/views.py
Labels: type: bug
